# Generated by Django 5.2.11 on 2026-03-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_address_complaint_assigned_crew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-priority_score', '-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority_label',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority_score',
            field=models.IntegerField(default=50),
        ),
    ]
