# Generated by Django 5.2.11 on 2026-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaint_options_complaint_priority_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='upvote_count',
            field=models.IntegerField(default=1),
        ),
    ]
