# Generated by Django 5.2.11 on 2026-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_image_hash_complaint_upvote_count'),
        ('users', '0006_team_customuser_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='assigned_crew',
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_teams',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='users.team'),
        ),
    ]
