# Generated by Django 5.2.11 on 2026-03-09 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_remove_complaint_assigned_crew_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_individual_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
