# Generated by Django 5.2.11 on 2026-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('PWD', 'PWD – Roads & Infrastructure'), ('SANITATION', 'Sanitation'), ('ELECTRICITY', 'Electricity'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
