# Generated by Django 5.2.11 on 2026-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_add_department_to_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='near_sensitive_location',
            field=models.BooleanField(default=False, help_text='True if the complaint was reported within 500m of a school or hospital.'),
        ),
    ]
