# Generated by Django 5.2.11 on 2026-03-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_add_near_sensitive_location'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='complaint',
                    name='near_sensitive_location',
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='SensitiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(help_text='Total number of detected sensitive places')),
                ('name_sensitive_location', models.CharField(max_length=255)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_locations', to='complaints.complaint')),
            ],
        ),
    ]
