# Generated by Django 5.2.11 on 2026-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_sensitive_location_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivelocation',
            name='name_sensitive_location',
            field=models.JSONField(default=list, help_text='List of names of the sensitive locations'),
        ),
    ]
