# Generated by Django 5.2.11 on 2026-03-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_sensitive_location_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensitivelocation',
            name='name_sensitive_location',
            field=models.JSONField(blank=True, help_text="List of names, 'error', or null", null=True),
        ),
    ]
