# Generated by Django 5.2.11 on 2026-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_drop_near_sensitive_location_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='genuinity_status',
            field=models.CharField(choices=[('Verified', 'Verified (Match)'), ('Unverified', 'Unverified (Missing Data)'), ('Flagged', 'Flagged (Mismatch)')], default='Unverified', help_text='Result of EXIF GPS metadata verification', max_length=20),
        ),
    ]
