# Generated by Django 5.2.11 on 2026-04-15 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_complaint_genuinity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority_tier',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', help_text='SLA tier (Critical/High/Medium/Low) – drives SLA deadline', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_breach_notified',
            field=models.BooleanField(default=False, help_text='True once an SLA breach alert has been dispatched'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='created_at + tier hours; refreshed on tier escalation', null=True),
        ),
        migrations.CreateModel(
            name='SLABreachLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(help_text="e.g. 'SLA breached – unresolved after 8 hours (High)' or 'Escalated Low→Medium'", max_length=255)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_breach_logs', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
