# Generated by Django 5.2.11 on 2026-04-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_complaint_priority_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='priority_tier',
        ),
    ]
