# Generated by Django 5.2.11 on 2026-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0018_remove_complaint_priority_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, help_text='Set each time priority is escalated by the SLA scheduler', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, help_text='Set ONCE at creation (created_at + tier hours). Never reset during escalation.', null=True),
        ),
    ]
