# Generated by Django 5.2.11 on 2026-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_add_last_escalated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution_notified',
            field=models.BooleanField(default=False, help_text='True once a resolution-breach in-app notification has been dispatched'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Set ONCE at creation (created_at + response hours). Response-phase deadline.', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='response_notified',
            field=models.BooleanField(default=False, help_text='True once a response-phase warning notification has been dispatched'),
        ),
    ]
