# Generated by Django 5.2.11 on 2026-03-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='resolved_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('CREW', 'Field Crew'), ('ADMIN', 'System Admin')], default='CITIZEN', max_length=10),
        ),
    ]
