# Generated by Django 5.2.11 on 2026-03-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_phone_number_customuser_resolved_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ROAD', 'Road Maintenance'), ('SANITATION', 'Sanitation & Waste'), ('ELECTRICAL', 'Electrical & Lighting'), ('WATER', 'Water & Drainage'), ('PARKS', 'Parks & Public Spaces'), ('GENERAL', 'General Maintenance')], max_length=20, null=True),
        ),
    ]
