# Generated by Django 5.2.11 on 2026-03-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(blank=True, choices=[('ROAD', 'Road Maintenance'), ('SANITATION', 'Sanitation & Waste'), ('ELECTRICAL', 'Electrical & Lighting'), ('WATER', 'Water & Drainage'), ('PARKS', 'Parks & Public Spaces'), ('GENERAL', 'General Maintenance')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.team'),
        ),
    ]
