# Generated by Django 5.2.11 on 2026-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_team_customuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ROAD', 'Road Maintenance'), ('SANITATION', 'Sanitation & Waste'), ('ELECTRICAL', 'Electrical & Lighting')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, choices=[('ROAD', 'Road Maintenance'), ('SANITATION', 'Sanitation & Waste'), ('ELECTRICAL', 'Electrical & Lighting')], max_length=20, null=True),
        ),
    ]
