# Generated by Django 5.2.11 on 2026-03-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_department_alter_team_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('ROAD', 'Road Maintenance'), ('SANITATION', 'Sanitation & Waste'), ('ELECTRICAL', 'Electrical & Lighting'), ('WATER', 'Water & Drainage'), ('PARKS', 'Parks & Public Spaces'), ('GENERAL', 'General Maintenance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='department',
            field=models.CharField(blank=True, choices=[('ROAD', 'Road Maintenance'), ('SANITATION', 'Sanitation & Waste'), ('ELECTRICAL', 'Electrical & Lighting'), ('WATER', 'Water & Drainage'), ('PARKS', 'Parks & Public Spaces'), ('GENERAL', 'General Maintenance')], max_length=20, null=True),
        ),
    ]
