# Generated by Django 5.2.11 on 2026-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_department_alter_team_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('CREW', 'Field Crew'), ('ADMIN', 'System Admin'), ('PWD', 'PWD Department'), ('SANITATION', 'Sanitation Department'), ('ELECTRICITY', 'Electricity Department')], default='CITIZEN', max_length=20),
        ),
    ]
