# Generated by Django 5.2.11 on 2026-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('response_warning', 'Response Warning'), ('resolution_warning', 'Resolution Warning'), ('breach', 'Breach')], default='general', help_text='Category of notification for UI badge display', max_length=30),
        ),
    ]
