# Generated by Django 5.2.11 on 2026-04-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_supervisor',
            field=models.BooleanField(default=False, help_text='True if this user is a Team Supervisor'),
        ),
    ]
