# Generated by Django 5.2.11 on 2026-04-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Chennai', help_text='Base city or operational zone', max_length=100),
        ),
    ]
